version: '3.4'

services:
  sandbox:
    image: ghcr.io/untitlecms/python-sandbox:v0
    env_file:
      - .env 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./code:/sourcecode
      - ./config/authorized_keys:/config/authorized_keys
    ports:
      - "7777:2222"
